language: 'ko-KR'
early_access: true
enable_free_tier: true
reviews:
  profile: 'chill'
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai 요약'
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true
