services:
  mysql:
    image: 'mysql:latest'
    container_name: 'local-mysql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'redis-practice'
  redis:
    image: 'redis:latest'
    container_name: 'local-redis'
    command: redis-server --port 6379
    ports:
      - '6379:6379'
