name: NestJS CI/CD with Docker and EC2

on:
  push:
    branches: ['main']

jobs:
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/my-nest-app:latest
            ${{ secrets.DOCKER_USERNAME }}/my-nest-app:${{ github.sha }}

  deploy:
    name: Deploy to EC2
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-nest-app:${{ github.sha }}
            docker stop my-nest-app-container || true
            docker rm my-nest-app-container || true
            docker run -d --name my-nest-app-container -p 80:3000 \
              --restart always \
              ${{ secrets.DOCKER_USERNAME }}/my-nest-app:${{ github.sha }}
